# Generated by Django 4.1.13 on 2024-09-13 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('age', models.IntegerField(help_text='Enter your age (must be between 18 and 100)', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Select your gender', max_length=1)),
                ('relationship_status', models.CharField(choices=[('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed')], help_text='Select your current relationship status', max_length=1)),
                ('looking_for', models.CharField(choices=[('LT', 'Long-term'), ('ST', 'Short-term'), ('F', 'Friendship'), ('C', 'Casual')], help_text="Select what kind of relationship you're looking for", max_length=2)),
                ('settle_timeline', models.IntegerField(help_text='Enter your timeline to settle down in months (0-60)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('occupation', models.CharField(help_text='Enter your current occupation', max_length=100)),
                ('interests', models.TextField(blank=True, help_text='Enter your interests, separated by commas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(help_text='The compatibility score between the two profiles (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason', models.TextField(help_text='The reason for the match, generated by the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile1', models.ForeignKey(help_text='The first profile in the match', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile1', to='matchmaker.profile')),
                ('profile2', models.ForeignKey(help_text='The second profile in the match', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile2', to='matchmaker.profile')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-compatibility_score', '-created_at'],
            },
        ),
    ]
